### ISSUE TITLE
Dashboard: Make header responsive

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#542]
I like to put the dashboard on the right 1/3 of my screen with NotePlan taking the left 2/3. The problem is that the headings don't reduce well with the size of the window. When you refactor, can you please make the top part of the page more responsive?

<img width="525" alt="Screen Cap 2024-03-07 at 11 33 51@2x" src="https://github.com/NotePlan/plugins/assets/8949588/302ac6e9-483b-4ae1-afa7-6eceb8b946b8">

I would suggest, under a certain breakpoint (e.g. <800px):
1) hide the text "8 open items; 6 closed." altogether
2) hide the "filter out lower priority items" button altogether
2) make the "last updated" text and the refresh button smaller (they should not have as much importance as the tasks to be accomplished) 

w/r/t to responsive hiding, this kind of code will help:
```css
@media only screen and (max-width: 800px) {
  .div-name-to-hide {
    display: none;
  }
}
```
